### ISSUE TITLE
'+' signs are removed from file names when running pytest

### ISSUE THREAD

**Issue by eyvorchuk** [pacificclimate/thunderbird#19]
The file name of the test `pr` netcdf file on THREDDS is
`pr_day_BCCAQv2+ANUSPLIN300_NorESM1-M_historical+rcp26_r1i1p1_19500101-19501231.nc`
(the full URL is
`http://docker-dev03.pcic.uvic.ca:8083/twitcher/ows/proxy/thredds/dodsC/datasets/TestData/pr_day_BCCAQv2+ANUSPLIN300_NorESM1-M_historical+rcp26_r1i1p1_19500101-19501231.nc`)
and the `tasmin` and `tasmax` files are named similarly.

[When the URLs to these files are passed as parameters to the wps process using pytest](https://github.com/pacificclimate/thunderbird/blob/980a06ba70fbf266b70f392f8482e8df71fcd360/tests/test_wps_generate_prsn.py#L86), the `pr` file name instead becomes
`pr_day_BCCAQv2 ANUSPLIN300_NorESM1-M_historical rcp26_r1i1p1_19500101-19501231.nc`
and the `tasmin` and `tasmax` files are named similarly.

[I've modified the wps process to replace these spaces with '+' when needed](https://github.com/pacificclimate/thunderbird/blob/980a06ba70fbf266b70f392f8482e8df71fcd360/thunderbird/processes/wps_generate_prsn.py#L230), but ideally, they shouldn't be removed to begin with.

**Comment by jameshiebert** [comment]
There is a set of [reserved characters](https://en.wikipedia.org/wiki/Percent-encoding#Percent-encoding_reserved_characters) that have special semantic meaning when used in a URL. `+` is among the set. Therefore, if the `+` symbol is part of the content of the URL it needs to be [urlencoded](https://docs.python.org/3.8/library/urllib.parse.html#urllib.parse.urlencode) before use. `+` -> `%2B`.

**Comment by eyvorchuk** [comment]
Worked like a charm. Thanks!
