### ISSUE TITLE
Inconsistent NetCDF behaviour

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/thunderbird#41]
When `thunderbird` is run as an additional component in `birdhouse-deploy` the `netcdf` files are not recognized.  This is not a problem with the instance of `bh-d` itself as other birds are able to use `netcdf` files without this issue.

**Comment by nikola-rados** [comment]
Now that we have sorted out the `cert` issues with the server settings, here is a look at the new error output:
```
Dry Run
File: https://docker-dev03.pcic.uvic.ca/twitcher/ows/proxy/thredds/dodsC/datasets/TestData/fdd_seasonal_CanESM2_rcp85_r1i1p1_1951-2100.nc
OSError: NetCDF: Not a valid data type or _FillValue type mismatch
```

Steps to reproduce this error:
1. Ensure you are on the UVic VPN
2. In your browser navigate to [https://docker-dev03.pcic.uvic.ca/](https://docker-dev03.pcic.uvic.ca/)
3. Copy and paste the cells from the [`thunderbird` demo](https://github.com/pacificclimate/thunderbird/blob/master/notebooks/demo.ipynb)
4. Run the cells
**Note:** You will not get past the dry run section

So it looks like this issue stems from the `netCDF4` package and the discrepancy between the version in `thunderbird` and the version on `jupyter hub`. `thunderbird` is getting that version from the [`nchelpers requirements.txt`](https://github.com/pacificclimate/nchelpers/blob/master/requirements.txt#L2) (`1.3.0`), which has not been updated in almost 2 years.  The version number that is installed by default in the `jupyter hub` instance from `bh-d` is `1.5.3`.  Looking at the `netCDF4` [changelog](https://github.com/Unidata/netcdf4-python/blob/master/Changelog) there are a number of references to how `_FillValue` is handled. From some testing it looks like there are some files that work fine, so it may be an issue of how the data was built/processed.

Off the top of my head I can think of a couple of different steps to take:
1. Update `netCDF4` version in `nchelpers`
This is the first thing that comes to mind but it is a little frightening.  The package version has been pinned for a long time and I'm not sure how many different tools/scripts/files would be impacted by this change.  It _could_ be the case that everything would change over smoothly, but I have a feeling there will be some side-effects.

2. Fix files
The `_FillValue` needs to be updated so that we can use the data. I'm not exactly sure how much work this would be.  It may be the case that **just** the metadata needs to be changed, but it could be that each occurrence of `_FillValue` in the `netcdf` file would need to be adjusted.  Depending on how much work it is we may want to write a script to handle this in `ce-dataprep`. That way any time we come across broken data there is a fast and repeatable way to fix it.

3. Implement a hack
There is a [hack](https://github.com/Unidata/netcdf4-python/issues/929#issuecomment-602091340) that works to negate this error.  This could be implemented while we sort out the larger problem.  Based on some shallow tests it seems appending `#fillmismatch` to each opendap url would circumvent the issue for now.

**Comment by corviday** [comment]
I have seen a similar error before. In that case, it was cased by a data packing process, which had changed the data type of the variable, but not of the fill value. Some - but not all - netCDF tools object to fill values that are a different type than the data values. 

If you do `ncdump`on the file, what is the type of the fill value attribute (letter at end of the numeric value)? Does it match the type of the data attribute?

When last I saw this issue, I just fixed the data by changing the fill value with `ncatted`, which lets you set the type of an attribute. It was fairly straightforward.

**Comment by nikola-rados** [comment]
> If you do `ncdump` on the file, what is the type of the fill value attribute (letter at end of the numeric value)?

```bash
(venv) nrados@pcic-2024:~/data$ ncdump -h fdd_seasonal_CanESM2_rcp85_r1i1p1_1951-2100.nc | grep _FillValue
		fdd:_FillValue = -32768. ;
```

> Does it match the type of the data attribute?

I'm not sure what you mean by this. The attribute in this particular case is `fdd` so I assume it would also be a numerical value.

> When last I saw this issue, I just fixed the data by changing the fill value attribute with `ncatted`, which lets you set the type of an attribute.

Is this in `data-prep-actions` somewhere?

> all I had to do was change the type of the attribute. It was fairly straightforward.

Ok, glad to hear that.  In that case then do you think I should not worry about updating `nchelpers`? If so, I would probably add `netCDF4==1.5.3` to the requirements to ensure `pytest` is running with the same env that the notebooks are.

**Comment by corviday** [comment]
Here's a section of ncdump output from a climatology:

```
	float streamflow(time, lat, lon) ;
		streamflow:long_name = "Streamflow at outlet grid cell" ;
		streamflow:units = "m3/s" ;
		streamflow:_FillValue = 9.96921e+36f ;
		streamflow:missing_value = 9.96921e+36f ;
		streamflow:cell_methods = "time: mean within days time: mean over days" ;
```

You can see that streamflow is a float from the first line, that is - the data stored inside the file is a collection of floats. You can see that the `_FillValue` attribute is also a float, because it ends with `f`.

Here's your file:
```
	float fdd(time, lat, lon) ;
		fdd:units = "degree days" ;
		fdd:_FillValue = -32768. ;
		fdd:standard_name = "FDD" ;
		fdd:long_name = "FDD" ;
		fdd:cell_methods = "time: sum within years" ;
```

In your file, `fdd` is also a float, but its fill value is not a float (missing the `f` at the end of the number). I think it's a double, but I'm not 100% sure what "no type marker" means. This is a mistake in the file. I do not know whether you should update `nchelpers`, but I do know should update this attribute. There are other netCDF tools that will refuse to work with files that have this problem.

**Comment by nikola-rados** [comment]
Ok thanks @corviday!

**Comment by corviday** [comment]
> Update netCDF4 version in nchelpers
> This is the first thing that comes to mind but it is a little frightening. The package version has been pinned for a long time and I'm not sure how many different tools/scripts/files would be impacted by this change. It could be the case that everything would change over smoothly, but I have a feeling there will be some side-effects.

If I recall correctly, the reason we pinned `netcdf4` at 1.3 is that starting in 1.4, all variables were treated as MaskedArrays. Previously, a variable was only treated as a MaskedArray if it actually had any masked or missing data (that is, if it had a fill value set and present in the data). This change broke some stuff in the PCEX backend, not sure if it would affect nchelpers, but the odds seem high.

**Comment by nikola-rados** [comment]
I think I may be able to avoid updating `nchelpers` by pinning the newest version of `netCDF4` in `thunderbird`.
