### ISSUE TITLE
Missing demo_decompose_flow_vectors in demo_individual

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/thunderbird#58]
While a demo run for decompose_flow_vectors is included in `demo_processes.ipynb`, an individual demo file is missing.

**Comment by nikola-rados** [comment]
@sum1lim I've opened an issue #54 to remove the individual demos.  I don't think they are necessary since they are just the same code repeated.

**Comment by sum1lim** [comment]
@nikola-rados Right, I did not see that issue. Thanks for the notification
