### ISSUE TITLE
Variable split_intervals is never used in wps_generate_climos

### ISSUE THREAD

**Issue by sum1lim** [pacificclimate/thunderbird#68]
`wps_generate_climos` takes an input [split_intervals](https://github.com/pacificclimate/thunderbird/blob/master/thunderbird/processes/wps_generate_climos.py#L190) but is never used when `thunderbird.generate_climos` is called. I believe [generate_climos](https://github.com/pacificclimate/climate-explorer-data-prep#usage) use this option for splitting the output files depending on time intervals. If this option will not be used in thunderbird, I think it should be removed from the input options.

**Comment by rod-glover** [comment]
Keep the option, and pass it into `create_climo_files`.
