### ISSUE TITLE
Wrap `update_metadata` into process

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/thunderbird#8]
[`update_metadata`](https://github.com/pacificclimate/climate-explorer-data-prep/blob/master/dp/update_metadata.py) is a `climate-explorer-data-prep` component that updates `netCDF` metadata using a `yaml`.

Wrap this functionality into a WPS.

**Comment by jameshiebert** [comment]
As noted in the script's docstring, the script proper updates metadata in-place. For the WPS version of the script, we will want to copy the netCDF file to a temporary location, modify it and return it as an output. I don't think that there's really any provision in a WPS workflow for modifying existing data iun place is there?

It would also be ideal if the YAML for the [`--updates`](https://github.com/pacificclimate/climate-explorer-data-prep/blob/master/scripts/update_metadata#L22) parameter could optionally be passed in as a string (not a file upload).

**Comment by nikola-rados** [comment]
> I don't think that there's really any provision in a WPS workflow for modifying existing data iun place is there?

I don't believe so, but there looks to be some work done recently to translate [`nc` files to `dap`](https://github.com/bird-house/emu/blob/master/emu/processes/wps_nc_to_dap.py).  Potentially we may be able to pull the `nc` file in, update the metadata and reupload it to the server. It seems they aren't yet sure how it will work just yet but it may be something to keep an eye on.
