### ISSUE TITLE
Update repo with cruft

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/thunderbird#85]
Cookiecutter has seen some updates since we created the bird. Update the repo using the cruft tool.

**Comment by tlvu** [comment]
PR https://github.com/bird-house/cookiecutter-birdhouse/pull/96 should be merged by the end of this week, just waiting to rollout the change to Raven, Finch, FlyingPigeon, Emu and make sure they all work and backport all necessary changes back to the cookiecutter to ease adoption for other birds.

So wait for this PR to be merged before proceeding here.

**Comment by nikola-rados** [comment]
Sounds good! I'll keep an eye on the PR.

**Comment by tlvu** [comment]
PR https://github.com/bird-house/cookiecutter-birdhouse/pull/96 is merged.  In that PR, there is reference to the different PR for different birds (Raven, Finch, FlyingPigeon, Emu) that have the new cookiecutter applied so you can see sample for dealing with the different docs build warnings.  Hopefully I've meet them all so you do not have to spend time digging (not all warnings fix can be backported to the cookiecutter so check those birds PR out).

It requires a pywps fix (PR https://github.com/geopython/pywps/pull/542) and that PR is not merged yet, let alone a new pywps release.  So if you have other things on your plate, you might want to wait until that PR is merged and a new pywps release is available.  However, if you are eager to apply the new cookiecutter, FlyingPigeon and Emu have the pywps PR installed from source to avoid waiting for PR merge and release is available.

**Comment by tlvu** [comment]
In fact, Raven and Finch did not need that Pywps PR so you might be luck, who knows.

**Comment by tlvu** [comment]
Pywps 4.2.7 is released.  You can proceed with this task.
